//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNew
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class projectEntities1 : DbContext
    {
        public projectEntities1()
            : base("name=projectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<ClientBillDetail> ClientBillDetails { get; set; }
        public virtual DbSet<ClientBill> ClientBills { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<MeasuringUnit> MeasuringUnits { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<RepresentitiveBillDetail> RepresentitiveBillDetails { get; set; }
        public virtual DbSet<RepresentitiveBill> RepresentitiveBills { get; set; }
        public virtual DbSet<Representitive> Representitives { get; set; }
        public virtual DbSet<SupplyerBillDetail> SupplyerBillDetails { get; set; }
        public virtual DbSet<SupplyerBill> SupplyerBills { get; set; }
        public virtual DbSet<Supplyer> Supplyers { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
