//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ClientBillDetails = new HashSet<ClientBillDetail>();
            this.MeasuringUnits = new HashSet<MeasuringUnit>();
            this.RepresentitiveBillDetails = new HashSet<RepresentitiveBillDetail>();
            this.SupplyerBillDetails = new HashSet<SupplyerBillDetail>();
            this.Supplyers = new HashSet<Supplyer>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public double AmountInStock { get; set; }
        public double AmountSaled { get; set; }
        public double WholesalePrice { get; set; }
        public double RetailPrice { get; set; }
        public Nullable<int> CategoryObj_ID { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientBillDetail> ClientBillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeasuringUnit> MeasuringUnits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepresentitiveBillDetail> RepresentitiveBillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyerBillDetail> SupplyerBillDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supplyer> Supplyers { get; set; }
    }
}
