//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class RepresentitiveBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RepresentitiveBill()
        {
            this.RepresentitiveBillDetails = new HashSet<RepresentitiveBillDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Representitive_NationalID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RepresentitiveBillDetail> RepresentitiveBillDetails { get; set; }
        public virtual Representitive Representitive { get; set; }
    }
}
