//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyerBillDetail
    {
        public int ID { get; set; }
        public double Amount { get; set; }
        public System.DateTime Date { get; set; }
        public double Paid { get; set; }
        public double Debt { get; set; }
        public string PurchaseType { get; set; }
        public double AmountPrice { get; set; }
        public Nullable<int> productOpj_ID { get; set; }
        public Nullable<int> SupplyerBillobj_ID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual SupplyerBill SupplyerBill { get; set; }
    }
}
