//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectNew
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyerBill
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplyerBill()
        {
            this.SupplyerBillDetails = new HashSet<SupplyerBillDetail>();
        }
    
        public int ID { get; set; }
        public double DeptPrice { get; set; }
        public double PaidPrice { get; set; }
        public Nullable<int> supplyer_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyerBillDetail> SupplyerBillDetails { get; set; }
        public virtual Supplyer Supplyer { get; set; }
    }
}
